WIP: Add TLS support to Prometheus Pushgateway
canonical/prometheus-pushgateway-k8s-operator pull request #15
Opened 2023-09-16 00:15 UTC by Abuelodelanada

## Issue

This PR add TLS support to the charm

## Testing Instructions

Run this Bundle:

```yaml
bundle: kubernetes
applications:
  ca:
    charm: self-signed-certificates
    channel: edge
    revision: 30
    scale: 1
    constraints: arch=amd64
  prometheus:
    charm: prometheus-k8s
    channel: edge
    revision: 148
    series: focal
    resources:
      prometheus-image: 126
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  pushgateway:
    charm: local:prometheus-pushgateway-k8s-9
    scale: 1
    constraints: arch=amd64
    storage:
      pushgateway-store: kubernetes,1,1024M
    trust: true
relations:
- - ca:certificates
  - prometheus:certificates
- - ca:certificates
  - pushgateway:certificates
- - prometheus:metrics-endpoint
  - pushgateway:metrics-endpoint
```

Run itests, and unit test

2023-09-19 00:09 UTC, sed-i commented on tests/integration/test_prometheus_integration.py
> +    for i in range(20):
Could be cleaner to sleep slightly more than the default scrape period (60s), e.g. 80s.

2023-09-19 00:09 UTC, sed-i commented on tests/integration/test_prometheus_integration.py
> +        labels = await prometheus.labels()
Iiuc, at this point you cannot use `prometheus` anymore because it was created before the CA relation.
Re-init the object?

2023-09-19 00:09 UTC, sed-i commented on tests/integration/test_prometheus_integration.py
> +            "prometheus-k8s",
Prom is deployed here again without cleaning up the model from the previous test method.
But instead cleanup, perhaps move to a separate file?

2023-09-19 12:02 UTC, Abuelodelanada commented on lib/charms/prometheus_pushgateway_k8s/v0/pushgateway.py
> +    def __init__(self, charm: CharmBase, relation_name: str, endpoint: str):
Seems like `http://127.0.0.1:9091` could be a good alternative as a default value

2023-09-19 16:18 UTC, Abuelodelanada commented on metadata.yaml
> +      The same CA cert is used for all in-cluster requests, e.g.:
Perhaps this is a future feature we can add later

2023-09-19 16:38 UTC, Abuelodelanada commented on src/charm.py
> +            return
Do you mean `can_connect()`?

We are executing this in every place which needs to talk to the workload:

- `_tls_ready`
- `_configure()`
- `_update_certs()`

There is no `can_connect()` guard in `_handle_web_config()` nor in `_set_pebble_layer()` as they are only called from `_configure()`.

Or am I missing something?

2023-09-20 17:58 UTC, Abuelodelanada commented on lib/charms/prometheus_pushgateway_k8s/v0/pushgateway.py
> +        relation_data[RELATION_KEY] = json.dumps({"url": self.endpoint})
I'm not sure, as the data we are updating is very simple, from my point of view this way is more explicit.

2023-09-20 18:48 UTC, sed-i approved these changes

2023-09-20 18:48 UTC, sed-i commented on src/charm.py
> +            return
I meant `_update_certs`: imagine a startup sequence were pebble-ready is emitted last (and that can_connect is False until then). We won't have certs unless `_update_certs` is also called from pebble-ready.

2023-09-21 13:13 UTC, PietroPasotti requested changes
if the integration tests pass with prometheus what's the point of the `testingcharm` charm?
If its only purpose is manual tests, it shouldn't be in the repo.

Besides, the testingcharm errors out on install. Because, I guess, the libraries from the 'root' charm are not copied into the pack folder.

2023-09-21 17:52 UTC, Abuelodelanada commented on src/charm.py
> +        self._container.exec(["update-ca-certificates", "--fresh"]).wait()
Well, this is a good question.

If this command ends with an error and we set the unit in `BlockedStatus`, is the Juju admin able to fix it in any way?

As far as I understand the answer is no. The errors can be that the binary `update-ca-certificates` is not there or there is an issue with the certificate itself. That's why I did not catch the exception here and let the charm go into `ErrorStatus`

What do you think @sed-i ?

2023-09-21 17:59 UTC, Abuelodelanada commented
> if the integration tests pass with prometheus what's the point of the `testingcharm` charm? If its only purpose is manual tests, it shouldn't be in the repo.

As far as I understand the main reason to include the `testingcharm` was to mimic a charm that instruments the [`send_metric() method`](https://github.com/canonical/prometheus-pushgateway-k8s-operator/blob/4edb3e5062ca9ce09d7e1c48309a1e60e03ac7b4/lib/charms/prometheus_pushgateway_k8s/v0/pushgateway.py#L228) as [an action](https://github.com/canonical/prometheus-pushgateway-k8s-operator/blob/4edb3e5062ca9ce09d7e1c48309a1e60e03ac7b4/tests/testingcharm/src/charm.py#L31)

> 
> Besides, the testingcharm errors out on install. Because, I guess, the libraries from the 'root' charm are not copied into the pack folder.

The lib [is copied on the fly while running the itest](https://github.com/canonical/prometheus-pushgateway-k8s-operator/blob/4edb3e5062ca9ce09d7e1c48309a1e60e03ac7b4/tests/integration/conftest.py#L55). I guess the idea behind this is to always have one version of the lib in the repo.

2023-09-21 18:08 UTC, Abuelodelanada commented on lib/charms/prometheus_pushgateway_k8s/v0/pushgateway.py
> +        ctx = ssl.create_default_context()
Harcoded path should be removed.

2023-09-21 18:29 UTC, sed-i commented on src/charm.py
> +        self._container.exec(["update-ca-certificates", "--fresh"]).wait()
Yeah I think we ended up saying that non-actionable errors (by the admin) like this should result in a traceback.

2023-09-22 07:51 UTC, PietroPasotti approved these changes
Looks good! Merge away :)

2023-09-22 15:41 UTC, merged